window.promoBox3 = {
  id: "promo-box-3",
  name: "Vault of Supremacy",
  fullName: "Vault of Supremacy",
  subtitle: "Promotional Card Box",
  description:
    "A premium vault of Super Rares and higher pulled from Duel Monsters era packs. Only the strongest and most iconic cards made it into this collection.",
  boxImage: "../assets/images/boxes/Promo Box III.png",
  imageBase: "../assets/images/promo-box-3/",
  cards: [
    // Section 7 - Secret
    { name: "Manticore of Darkness", chance: 0.1, section: 7 },

    // Section 1 - Gold
    { name: "Black Luster Soldier - Envoy of the Beginning", chance: 0.25, section: 1 },
    { name: "Chaos Emperor Dragon - Envoy of the End", chance: 0.2, section: 1 },
    { name: "Dimension Fusion", chance: 0.3, section: 1 },
    { name: "Fiber Jar", chance: 0.3, section: 1 },
    { name: "Heavy Storm", chance: 0.35, section: 1 },
    { name: "Imperial Order", chance: 0.2, section: 1 },
    { name: "Last Turn", chance: 0.3, section: 1 },
    { name: "Mirror Force", chance: 0.3, section: 1 },
    { name: "Royal Decree", chance: 0.25, section: 1 },
    { name: "Solemn Judgment", chance: 0.25, section: 1 },

    // Section 2 - Red
    { name: "Breaker the Magical Warrior", chance: 0.5, section: 2 },
    { name: "Call of the Haunted", chance: 0.5, section: 2 },
    { name: "Change of Heart", chance: 0.5, section: 2 },
    { name: "Dark Magician of Chaos", chance: 0.5, section: 2 },
    { name: "Dust Tornado", chance: 0.5, section: 2 },
    { name: "Exiled Force", chance: 0.5, section: 2 },
    { name: "Injection Fairy Lily", chance: 0.5, section: 2 },
    { name: "Jinzo", chance: 0.5, section: 2 },
    { name: "Magic Jammer", chance: 0.5, section: 2 },
    { name: "Marauding Captain", chance: 0.5, section: 2 },
    { name: "Mobius the Frost Monarch", chance: 0.5, section: 2 },
    { name: "Morphing Jar", chance: 0.5, section: 2 },
    { name: "Nobleman of Crossout", chance: 0.5, section: 2 },
    { name: "Premature Burial", chance: 0.5, section: 2 },
    { name: "Reinforcement of the Army", chance: 0.5, section: 2 },
    { name: "Seven Tools of the Bandit", chance: 0.5, section: 2 },
    { name: "Thousand-Eyes Restrict", chance: 0.5, section: 2 },
    { name: "Tribe-Infecting Virus", chance: 0.5, section: 2 },
    { name: "Tribute to the Doomed", chance: 0.5, section: 2 },

    // Section 3 - Pink
    { name: "Barrel Dragon", chance: 0.7, section: 3 },
    { name: "Big Burn", chance: 0.7, section: 3 },
    { name: "Catapult Turtle", chance: 0.7, section: 3 },
    { name: "Creature Swap", chance: 0.7, section: 3 },
    { name: "Dark Balter the Terrible", chance: 0.7, section: 3 },
    { name: "Dark Mirror Force", chance: 0.7, section: 3 },
    { name: "Dark Ruler Ha Des", chance: 0.7, section: 3 },
    { name: "Fiend Skull Dragon", chance: 0.7, section: 3 },
    { name: "Freed the Matchless General", chance: 0.7, section: 3 },
    { name: "Graverobber", chance: 0.7, section: 3 },
    { name: "Magical Hats", chance: 0.7, section: 3 },
    { name: "Mirror Wall", chance: 0.7, section: 3 },
    { name: "Ryu Senshi", chance: 0.7, section: 3 },
    { name: "Spell Shield Type-8", chance: 0.7, section: 3 },
    { name: "The Fiend Megacyber", chance: 0.7, section: 3 },
    { name: "Trap Jammer", chance: 0.7, section: 3 },

    // Section 4 - Purple
    { name: "Asura Priest", chance: 0.8, section: 4 },
    { name: "Backup Soldier", chance: 0.8, section: 4 },
    { name: "Ceasefire", chance: 0.8, section: 4 },
    { name: "D.D. Designator", chance: 0.8, section: 4 },
    { name: "D.D. Scout Plane", chance: 0.8, section: 4 },
    { name: "Dedication through Light and Darkness", chance: 0.8, section: 4 },
    { name: "Ectoplasmer", chance: 0.8, section: 4 },
    { name: "Freed the Brave Wanderer", chance: 0.8, section: 4 },
    { name: "Goblin Attack Force", chance: 0.8, section: 4 },
    { name: "Hallowed Life Barrier", chance: 0.8, section: 4 },
    { name: "Hino-Kagu-Tsuchi", chance: 0.8, section: 4 },
    { name: "Horus the Black Flame Dragon LV8", chance: 0.8, section: 4 },
    { name: "Invader of Darkness", chance: 0.8, section: 4 },
    { name: "Kuriboh", chance: 0.8, section: 4 },
    { name: "Levia-Dragon - Daedalus", chance: 0.8, section: 4 },
    { name: "Limiter Removal", chance: 0.8, section: 4 },
    { name: "Muko", chance: 0.8, section: 4 },
    { name: "Paladin of White Dragon", chance: 0.8, section: 4 },
    { name: "Sanga of the Thunder", chance: 0.8, section: 4 },
    { name: "Spell Canceler", chance: 0.8, section: 4 },
    { name: "Summoned Skull", chance: 0.8, section: 4 },
    { name: "Yata-Garasu", chance: 0.8, section: 4 },
    { name: "XYZ-Dragon Cannon", chance: 0.8, section: 4 },

    // Section 5 - Blue
    { name: "Airknight Parshath", chance: 1, section: 5 },
    { name: "Amazoness Archers", chance: 1, section: 5 },
    { name: "Beast of Talwar", chance: 1, section: 5 },
    { name: "Chain Destruction", chance: 1, section: 5 },
    { name: "Chaos Command Magician", chance: 1, section: 5 },
    { name: "Dark Paladin", chance: 1, section: 5 },
    { name: "Double Spell", chance: 1, section: 5 },
    { name: "Dragon Seeker", chance: 1, section: 5 },
    { name: "Drop Off", chance: 1, section: 5 },
    { name: "Exile of the Wicked", chance: 1, section: 5 },
    { name: "Fairy Meteor Crush", chance: 1, section: 5 },
    { name: "Horus the Black Flame Dragon LV6", chance: 1, section: 5 },
    { name: "Kazejin", chance: 1, section: 5 },
    { name: "Luster Dragon #2", chance: 1, section: 5 },
    { name: "Mystic Swordsman LV4", chance: 1, section: 5 },
    { name: "Orca-Mega Fortress of Darkness", chance: 1, section: 5 },
    { name: "Reload", chance: 1, section: 5 },
    { name: "Suijin", chance: 1, section: 5 },
    { name: "The Legendary Fisherman", chance: 1, section: 5 },
    { name: "Time Wizard", chance: 1, section: 5 },
    { name: "Twin-Headed Behemoth", chance: 1, section: 5 },
    { name: "Yamata Dragon", chance: 1, section: 5 },
    { name: "XY-Dragon Cannon", chance: 1, section: 5 },
    { name: "XZ-Tank Cannon", chance: 1, section: 5 },

    // Section 6 - White
    { name: "Amazoness Swordswoman", chance: 1.1, section: 6 },
    { name: "Armed Dragon LV7", chance: 1.1, section: 6 },
    { name: "Black Skull Dragon", chance: 1.1, section: 6 },
    { name: "Black Tyranno", chance: 1.1, section: 6 },
    { name: "Buster Blader", chance: 1.1, section: 6 },
    { name: "Call of the Grave", chance: 1.1, section: 6 },
    { name: "Chaosrider Gustaph", chance: 1.1, section: 6 },
    { name: "Dark Magician Girl", chance: 1.1, section: 6 },
    { name: "Diffusion Wave-Motion", chance: 1.1, section: 6 },
    { name: "Garnecia Elephantis", chance: 1.1, section: 6 },
    { name: "Gate Guardian", chance: 1.1, section: 6 },
    { name: "Gearfried the Iron Knight", chance: 1.1, section: 6 },
    { name: "Giant Red Seasnake", chance: 1.1, section: 6 },
    { name: "Greed", chance: 1.1, section: 6 },
    { name: "Guardian Angel Joan", chance: 1.1, section: 6 },
    { name: "Harpie Lady Sisters", chance: 1.1, section: 6 },
    { name: "Inferno Fire Blast", chance: 1.1, section: 6 },
    { name: "Insect Princess", chance: 1.1, section: 6 },
    { name: "Parasite Paracide", chance: 1.1, section: 6 },
    { name: "Penumbral Soldier Lady", chance: 1.1, section: 6 },
    { name: "Skilled Dark Magician", chance: 1.1, section: 6 },
    { name: "Skilled White Magician", chance: 1.1, section: 6 },
    { name: "Spear Dragon", chance: 1.1, section: 6 },
    { name: "Strike Ninja", chance: 1.1, section: 6 },
    { name: "Thousand Dragon", chance: 1.1, section: 6 },
    { name: "Twin-Headed Thunder Dragon", chance: 1.1, section: 6 },
    { name: "Tyrant Dragon", chance: 1.1, section: 6 },
    { name: "Wild Nature's Release", chance: 1.1, section: 6 },
    { name: "X-Head Cannon", chance: 1.1, section: 6 },
    { name: "Y-Dragon Head", chance: 1.1, section: 6 },
    { name: "Z-Metal Tank", chance: 1.1, section: 6 }
  ]
};