window.promoBox2 = {
  id: "promo-box-2",
  name: "Chaos Gamble",
  fullName: "Chaos Gamble",
  subtitle: "Promotional Card Box",
  description:
    "A wildly unpredictable collection of cards ranging from absurdly powerful staples to hilariously terrible pulls. Every opening is a gamble — someone will celebrate, and someone else will regret everything.",
  boxImage: "../assets/images/boxes/Promo Box II.png",
  imageBase: "../assets/images/promo-box-2/",
  cards: [
    // Section 7 - Platinum
    { name: "Mystic Mine", chance: 0.1, section: 7 },

    // Section 1 - Gold
    { name: "Ghost Mourner & Moonlit Chill", chance: 0.1333, section: 1 },
    { name: "Ghost Reaper & Winter Cherries", chance: 0.1333, section: 1 },
    { name: "Ghost Sister & Spooky Dogwood", chance: 0.1333, section: 1 },
    { name: "Ghost Ogre & Snow Rabbit", chance: 0.1333, section: 1 },
    { name: "Ghost Belle & Haunted Mansion", chance: 0.1333, section: 1 },
    { name: "Ash Blossom & Joyous Spring", chance: 0.1333, section: 1 },

    // Section 2 - Red
    { name: "Delinquent Duo", chance: 0.3, section: 2 },
    { name: "The Forceful Sentry", chance: 0.3, section: 2 },
    { name: "Confiscation", chance: 0.3, section: 2 },

    // Section 3 - Pink
    { name: "Skill Drain", chance: 0.4583, section: 3 },
    { name: "Level Limit Area A", chance: 0.4583, section: 3 },
    { name: "Level Limit Area B", chance: 0.4583, section: 3 },
    { name: "Messenger Of Peace", chance: 0.4583, section: 3 },
    { name: "Marshmallon", chance: 0.4583, section: 3 },
    { name: "Spirit Reaper", chance: 0.4583, section: 3 },
    { name: "One Day Of Peace", chance: 0.4583, section: 3 },
    { name: "Scrap-Iron Scarecrow", chance: 0.4583, section: 3 },
    { name: "Macro Cosmos", chance: 0.4583, section: 3 },
    { name: "Neo-Spacian Dolphin", chance: 0.4583, section: 3 },
    { name: "Neo-Spacian Grand Mole", chance: 0.4583, section: 3 },
    { name: "Nightmare Steelcage", chance: 0.4583, section: 3 },

    // Section 4 - Purple
    { name: "Morphing Jar", chance: 0.8, section: 4 },
    { name: "Cyber Jar", chance: 0.8, section: 4 },
    { name: "Absorbing Jar", chance: 0.8, section: 4 },
    { name: "Aroma Jar", chance: 0.8, section: 4 },
    { name: "Cobra Jar", chance: 0.8, section: 4 },
    { name: "Dice Jar", chance: 0.8, section: 4 },
    { name: "Dimension Jar", chance: 0.8, section: 4 },
    { name: "Fiber Jar", chance: 0.8, section: 4 },
    { name: "Greed Jar", chance: 0.8, section: 4 },
    { name: "Morphing Jar #2", chance: 0.8, section: 4 },

    // Section 5 - Blue
    { name: "Aqua Madoor", chance: 0.9615, section: 5 },
    { name: "Battle Footballer", chance: 0.9615, section: 5 },
    { name: "Bitron", chance: 0.9615, section: 5 },
    { name: "Bunilla", chance: 0.9615, section: 5 },
    { name: "Chamberlain Of The Six Samurai", chance: 0.9615, section: 5 },
    { name: "Charcoal Inpachi", chance: 0.9615, section: 5 },
    { name: "Crowned By The World Chalice", chance: 0.9615, section: 5 },
    { name: "D.D. Trainer", chance: 0.9615, section: 5 },
    { name: "Earthbound Spirit", chance: 0.9615, section: 5 },
    { name: "Elemental Hero Clayman", chance: 0.9615, section: 5 },
    { name: "Gem-Knight Sapphire", chance: 0.9615, section: 5 },
    { name: "Giant Soldier Of Stone", chance: 0.9615, section: 5 },
    { name: "Humanoid Slime", chance: 0.9615, section: 5 },
    { name: "Island Turtle", chance: 0.9615, section: 5 },
    { name: "Melffy Rabby", chance: 0.9615, section: 5 },
    { name: "Mystical Elf", chance: 0.9615, section: 5 },
    { name: "Oppressed People", chance: 0.9615, section: 5 },
    { name: "Prevent Rat", chance: 0.9615, section: 5 },
    { name: "Renge, Gatekeeper Of The Dark World", chance: 0.9615, section: 5 },
    { name: "Skull Dog Marron", chance: 0.9615, section: 5 },
    { name: "Soul Tiger", chance: 0.9615, section: 5 },
    { name: "Spirit Of The Harp", chance: 0.9615, section: 5 },
    { name: "The Dragon Dwelling In The Cave", chance: 0.9615, section: 5 },
    { name: "Venom Cobra", chance: 0.9615, section: 5 },
    { name: "Flamvell Guard", chance: 0.9615, section: 5 },
    { name: "Guardragon Justicia", chance: 0.9615, section: 5 },

    // Section 6 - White
    { name: "Goblin Calligrapher", chance: 2.2111, section: 6 },
    { name: "Harpie Girl", chance: 2.2111, section: 6 },
    { name: "Kozaky", chance: 2.2111, section: 6 },
    { name: "Skull Servant", chance: 2.2111, section: 6 },
    { name: "Soitsu", chance: 2.2111, section: 6 },
    { name: "Aitsu", chance: 2.2111, section: 6 },
    { name: "Volcanic Rat", chance: 2.2111, section: 6 },
    { name: "Unicycler", chance: 2.2111, section: 6 },
    { name: "Turu-Purun", chance: 2.2111, section: 6 },
    { name: "Tomozaurus", chance: 2.2111, section: 6 },
    { name: "Thousand-Eyes Idol", chance: 2.2111, section: 6 },
    { name: "Shadow Specter", chance: 2.2111, section: 6 },
    { name: "Protron", chance: 2.2111, section: 6 },
    { name: "Petit Moth", chance: 2.2111, section: 6 },
    { name: "Mystical Shine Ball", chance: 2.2111, section: 6 },
    { name: "Mokey Mokey", chance: 2.2111, section: 6 },
    { name: "Key Mace", chance: 2.2111, section: 6 },
    { name: "Hieratic Seal Of The Sun Dragon Overlord", chance: 2.2111, section: 6 },
    { name: "Haniwa", chance: 2.2111, section: 6 },
    { name: "Gigobyte", chance: 2.2111, section: 6 },
    { name: "Flame Viper", chance: 2.2111, section: 6 },
    { name: "Doll Monster Miss Madchen", chance: 2.2111, section: 6 },
    { name: "Doll Monster Bear-Bear", chance: 2.2111, section: 6 },
    { name: "Dipity", chance: 2.2111, section: 6 },
    { name: "Dancing-Elf", chance: 2.2111, section: 6 },
    { name: "Change Slime", chance: 2.2111, section: 6 },
    { name: "Bokoichi The Freightening Car", chance: 2.2111, section: 6 }
  ]
};